### ISSUE TITLE
White text logo

### ISSUE THREAD

**Issue by hiferli** [hiferli/Startup-Scrapping#1]
I wanted to have a logo that contains text in white color.
However, I didn't find one. If someone with good picture editing skills can help me with the same, that would be awesome!
I would add your username in the @Authors tab in the README file :)

**Comment by lizzzshan** [comment]
Hi! I'd love to get that done for you! May I ask for more specifics on what you mean by "text in white color?" Is it just the logo or the text too?

**Comment by hiferli** [comment]
Acutally all I wan to do is replace the black color in the text of the logo with a white color text.
To be more precise, I need to invert the color of the text in the logo file.
